apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: persistent-volume-claim
spec:   #object customization
    accessModes:
        - ReadWriteOnce   #only accessed by a single Node
    resources:
        requests:
            storage: 1Gi