apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:                               #customization of the Service
  type: ClusterIP                   #type of Cluster IP
  elector:
      component: server
  ports:
      - port: 5000           #port to incoming traffic
      targetPort: 5000       #port for acessing the Pod with the selector label